config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get 'home/about' => 'homes#about', as: 'about'
  get 'search' => 'searches#search'
  devise_for :users

  resources :users, only: [:index, :show, :edit, :update] do
    get "search", to: "users#search"
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users
  has_one_attached :group_image

  validates :name, presence: true
  validates :introduction, presence: true

  def get_group_image(width, height)
  unless group_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    group_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  group_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    @group.users << current_user
    if @group.save
      redirect_to groups_path
    else
      render 'new'
    end
  end

  def index
    @book = Book.new
    @groups = Group.all
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to groups_path
    else
      render 'edit'
    end
  end

  def show
    @book = Book.new
    @group = Group.find(params[:id])
  end

  def join
    @group = Group.find(params[:group_id])
    @group.users << current_user
    redirect_to request.referer
  end

  def destroy
    @group = Group.find(params[:id])
    @group.users.delete(current_user)
    redirect_to request.referer
  end

  def new_mail
    @group = Group.find(params[:group_id])
  end

  def send_mail
    @group = Group.find(params[:group_id])
    group_users = @group.users
    @mail_title = params[:mail_title]
    @mail_content = params[:mail_content]
    ContactMailer.send_mail(@mail_title, @mail_content, group_users).deliver
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, :group_image)
  end

  def ensure_correct_user
    @group = Group.find(params[:id])
    unless @group.owner_id == current_user.id
      redirect_to groups_path
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Group</h1>
      <%= form_with model: @group do |f| %>
        <div class="form-group">
          <%= f.label :グループ名 %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :紹介文 %>
          <%= f.text_field :introduction, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :グループ画像 %><br>
          <%= f.file_field :group_image, accept: "image/*" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update Group', class: "btn btn-info" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="container">
  <div class="row">
    <%= render 'books/left', user: current_user, book: @book %>

    <div class="col-md-8 offset-md-1">
      <h1>Groups</h1>
      <table class="table table-hover table-inverse">
        <thead>
          <th></th>
          <th>グループ名</th>
          <th>紹介文</th>
          <th>メンバー数</th>
          <th></th>
        </thead>
        <% @groups.each do |group| %>
        <tbody>
          <tr>
            <td><%= image_tag group.get_group_image(50, 50) %></td>
            <td>
              <%= link_to group_path(group.id) do %>
                <%= group.name %>
              <% end %>
            </td>
            <td><%= group.introduction %></td>
            <td><%= group.users.count %></td>
            <% if group.owner_id == current_user.id %>
              <td><%= link_to "Edit", edit_group_path(group.id), class: "btn btn-sm btn-success" %></td>
            <% end %>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Create Group</h1>
      <%= form_with model: @group do |f| %>
        <div class="form-group">
          <%= f.label :グループ名 %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :紹介文 %>
          <%= f.text_area :introduction, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :グループ画像 %><br>
          <%= f.file_field :group_image, accept: "immage/*" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Create Group', class: "btn btn-info" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/new_mail.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <h2>Event Mail</h2>

      <%= form_with url: group_send_mail_path(@group), method: :get, local: true do |f| %>
        <div class="form-group">
          <%= f.label :Title %>
          <%= f.text_field :mail_title, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :Content %>
          <%= f.text_area :mail_content, class: 'form-control' %>
        </div>
        <div class="text-right">
          <%= f.submit '送信', class: 'btn btn-info' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/send_mail.html.erb
<div class="container">
  <h3 class="margin_top text-center">送信が完了しました</h3>
  <div class="main_width">
    <div class="row-4 offset-4">内容は以下の通りです。</div>
    <div class="row-4 offset-4">
      [タイトル]<p class="font-weight-bold"><%= @mail_title %></p>
    </div>
    <div class="row-4 offset-4">
      [本文]<p class="font-weight-bold"><%= safe_join(@mail_content.split("\n"), tag(:br)) %></p>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class="container">
  <div class="row">
    <%= render 'books/left', user: current_user, book: @book %>

    <div class="col-md-8 offset-md-1">
      <h1>Group Detail</h1>
      <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー</th>
            <th colspan="2"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= image_tag @group.get_group_image(50, 50) %></td>
            <td><%= @group.name %></td>
            <td><%= @group.introduction %></td>
            <td>
              <% @group.users.each do |group| %>
                <%= group.name %><br>
              <% end %>
            </td>
            <% if @group.owner_id == current_user.id %>
              <td><%= link_to "Edit", edit_group_path(@group.id), class: "btn btn-sm btn-success" %></td>
              <td><%= link_to "Notice an Event", group_new_mail_path(@group), class: "btn btn-sm btn-info" %></td>
            <% elsif @group.users.include?(current_user) %>
              <td><%= link_to "Leave this group", group_path(@group), method: :delete, class: "btn btn-sm btn-danger" %></td>
            <% else %>
              <td><%= link_to "Join this group", group_join_path(@group), class: "btn btn-sm btn-success" %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>