config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get 'home/about' => 'homes#about', as: 'about'
  get 'search' => 'searches#search'
  devise_for :users

  resources :users, only: [:index, :show, :edit, :update] do
    get "search", to: "users#search"
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :favorited_books, through: :favorites, source: :book

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  has_many :views, dependent: :destroy
  has_many :group_users, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true, uniqueness: true,
                   length: { maximum: 20, minimum: 2 }
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backward__match"
      @user = User.where("name LIKE?", "%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def index
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @currrentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
       @currrentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
    @two_days_ago = @books.created_two_days_ago
    @three_days_ago = @books.created_three_days_ago
    @four_days_ago = @books.created_four_days_ago
    @five_days_ago = @books.created_five_days_ago
    @six_days_ago = @books.created_six_days_ago
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
    render :edit
    end
  end

  def search
    @user = User.find(params[:user_id])
    @books = @user.books
    @book = Book.new
    if params[:created_at] == ""
      @search_book = "日付を選択して下さ"
    else
      create_at = params[:created_at]
      @search_book = @books.where(['created_at LIKE ?', "#{create_at}%"]).count
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image, :color)
  end



end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_search.html.erb
<h4>検索結果</h4>
  <table class='table table-bordered'>
    <thead>
      <tr>
        <th>投稿数</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= search_book %></td>
      </tr>
    </tbody>
  </table>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>

      <%= render 'books/error', model: @user %>

      <%= form_with model: @user do |f| %>
        <div class="form-group">
          <label for="user_name">Name</label>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <label for="user_image">Image</label>
          <%= f.file_field :profile_image, accept: "image/*", class: "form-control-file" %>
        </div>
        <div class="form-group">
          <label for="user-introduction">Introduction</label>
          <%= f.text_area :introduction, class: "form-control" %>
        </div>
        <div class="form-group">
          <label for="color">ヘッダーの色を変える</label>
          <%= f.select :color, [["赤", "red"], ["青", "blue"], ["緑", "green"]], {include_blank: current_user.color } %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update User', class: 'btn btn-secondary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 jx-sm-0">
  <div class="row">

    <%= render 'books/left', user: current_user, book: @book %>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <%= link_to "グループを作成する", new_group_path %> |
      <%= link_to "グループ一覧", groups_path %>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= image_tag user.get_profile_image(50,50) %></td>
              <td>
                <%= user.name %>
              </td>
              <td>
                フォロー数：<%= user.followings.count %>
              </td>
              <td>
                フォロワー数：<%= user.followers.count %>
              </td>
              <% if user.id == current_user.id %>
                <td></td>
              <% else %>
                <td>
                  <% if current_user.following?(user) %>
                    <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete %>
                  <% else %>
                    <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
                  <% end %>
                </td>
              <% end %>
              <td><%= link_to "Show", user_path(user.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/search.js.erb
$("#search_result").html("<%= j(render 'search', search_book: @search_book) %>");

app/views/users/show.html.erb
<div class="container">
  <div class="row">

  <%= render 'books/left', user: @user, book: @book, isRoom: @isRoom, room: @room, entry: @entry, roomId: @roomId %>

  <div class="col-md-8 offset-md-1">
    <h1>Books</h1>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
                <%= image_tag book.user.get_profile_image(50,50) %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td><%= book.body %></td>
            <td>
              <%= render 'books/rate', book: book %>
            </td>
            <td>閲覧数：<%= book.views.count %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <h4>投稿数の前日比・前週比</h4>
    <table class="table table-bordered">
      <thead>
        <th>今日の投稿</th>
        <th>前日の投稿</th>
        <th>前日比</th>
      </thead>
      <tbody>
        <td><%= @today_book.count %></td>
        <td><%= @yesterday_book.count %></td>
        <td>
          <% if @yesterday_book.count == 0 %>
            前日の投稿が0のため計算できません
          <% else %>
            <%= (@today_book.count/@yesterday_book.count.to_f * 100).round %>%
          <% end %>
        </td>
      </tbody>
    </table>

    <table class="table table-bordered">
      <thead>
        <th>今週の投稿</th>
        <th>前週の投稿</th>
        <th>前週比</th>
      </thead>
      <tbody>
        <td><%= @this_week_book.count %></td>
        <td><%= @last_week_book.count %></td>
        <td>
          <% if @last_week_book.count == 0 %>
            前週の投稿が0のため計算できません
          <% else %>
            <%= (@this_week_book.count / @last_week_book.count.to_f * 100).round %>%
          <% end %>
        </td>
      </tbody>
    </table>

    <h4>7日間分の投稿数</h4>
    <table class="table table-bordered">
      <thead>
        <th>6日前</th>
        <th>5日前</th>
        <th>4日前</th>
        <th>3日前</th>
        <th>2日前</th>
        <th>1日前</th>
        <th>今日</th>
      </thead>
      <tbody>
        <td><%= @six_days_ago.count %></td>
        <td><%= @five_days_ago.count %></td>
        <td><%= @four_days_ago.count %></td>
        <td><%= @three_days_ago.count %></td>
        <td><%= @two_days_ago.count %></td>
        <td><%= @yesterday_book.count %></td>
        <td><%= @today_book.count %></td>
      </tbody>
    </table>


    <canvas id="myChart"></canvas>
    <script>
      $(document).on('turbolinks:load', function() {
        var ctx = document.getElementById("myChart");
        var myChart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
                datasets: [{
                    label: '投稿した本の数',
                    data: [
                      <%= @six_days_ago.count %>,
                      <%= @five_days_ago.count %>,
                      <%= @four_days_ago.count %>,
                      <%= @three_days_ago.count %>,
                      <%= @two_days_ago.count %>,
                      <%= @yesterday_book.count %>,
                      <%= @today_book.count %>
                      ],
                    backgroundColor: "rgba(0, 0, 0, 0)",
                    borderColor: "rgba(0, 0, 255, 1)",
                    tension: 0.4
                }]
            },
            options: {
              title: {
                display: true,
                text: '7日間の投稿数の比較'
              },
              scales: {
                yAxes: [{
                    ticks: {
                        suggestedMin: 0,
                        suggestedMax: 10,
                        beginAtZero: true
                    }
                }]
              }
            }
          });
        });
    </script>
    <diV class="m-3">
      <%= form_with url: user_search_path(@user), method: :get, class: "row justify-content-center", local: false do |f| %>
        <div class="col-auto">
          <%= f.date_field :created_at, class: "form-control" %>
        </div>
        <div class="col-auto">
          <%= f.submit '検索', class: 'btn btn-primary btn-sm' %>
        </div>
      <% end %>
    </diV>

    <div id="search_result">
      <% if @search_book.present? %>
        <%= render 'search', search_book: @search_book %>
      <% end %>
    </div>

  </div>

  </div>
</div>