config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get 'home/about' => 'homes#about', as: 'about'
  get 'search' => 'searches#search'
  devise_for :users

  resources :users, only: [:index, :show, :edit, :update] do
    get "search", to: "users#search"
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :views, dependent: :destroy
  has_many :book_tags, dependent: :destroy
  has_many :tags, through: :book_tags

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  validates :rate, presence: true

  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }
  scope :created_two_days_ago, -> { where(created_at: 2.day.ago.all_day) }
  scope :created_three_days_ago, -> { where(created_at: 3.day.ago.all_day) }
  scope :created_four_days_ago, -> { where(created_at: 4.day.ago.all_day) }
  scope :created_five_days_ago, -> { where(created_at: 5.day.ago.all_day) }
  scope :created_six_days_ago, -> { where(created_at: 6.day.ago.all_day) }

  scope :fast, -> { order(created_at: :desc) }
  scope :rate_count, -> { order(rate: :desc) }


  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags -sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      self.book_tags.delete Tag.find_by(tag_name: old)
    end

    new_tags.each do |new|
      new_book_tag = Tag.find_or_create_by(tag_name: new)
      self.tags << new_book_tag
    end
  end


  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?", "#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?", "#{word}%")
    elsif search == "backward__match"
      @book = Book.where("title LIKE?", "%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?", "%#{word}%")
    else
      @book = Book.all
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    to = Time.current.at_end_of_day
    from = (to - 6.day).at_beginning_of_day

    if params[:fast]
      @books = Book.fast
    elsif params[:rate_count]
      @books = Book.rate_count
    else
      #includesは一回でbookに紐づいている情報を取り出せるようにするためのもの、ここではbookに紐づいている:favorited_usersを一回で呼び出す
      @books = Book.includes(:favorited_users).
      sort {|a,b|
        #whereはモデル名.where(カラム名: 条件)でcreate_atカラムからtoからfromまでをすべて取得
        b.favorited_users.includes(:favorites).where(created_at: from...to).size <=>
        a.favorited_users.includes(:favorites).where(created_at: from...to).size
      }
    end
    @book = Book.new
    @tags = Tag.all
  end

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
    @book_comment = BookComment.new
    @user = @book.user
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      unless @isRoom
        @room = Room.new
        @entry = Entry.new
      end
    end
    unless View.find_by(user_id: current_user.id, book_id: @book.id)
      current_user.views.create(book_id: @book.id)
    end

  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    tag_list = params[:book][:tag_name].split(',')
    if @book.save
      @book.save_tag(tag_list)
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :index
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :rate)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_error.html.erb
<% if model.errors.any? %>
  <%= model.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% model.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/books/_left.html.erb
<div class="col-md-3">

  <h2>User info</h2>

  <%= image_tag user.get_profile_image(100,100) %>

  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
      <tr>
        <th>follows</th>
        <th>
          <%= link_to user_followings_path(user) do %>
            <%= user.followings.count %>
          <% end %>
        </th>
      </tr>
      <tr>
        <th>followers</th>
        <th>
          <%= link_to user_followers_path(user) do %>
            <%= user.followers.count %>
          <% end %>
          </th>
      </tr>
    </tbody>
  </table>

  <% if user != current_user %>
    <% if current_user.following?(user) %>
      <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete, class: "btn btn-info" %>
      <% if (current_user.following?(user)) && (user.following?(current_user)) %>
        <% if isRoom == true %>
          <p class="user-show-room"><a href="/rooms/<%= roomId %>" class="btn btn-success my-2">チャットへ</a></p>
        <% else %>
          <%= form_with model: room do |f| %>
            <%= fields_for entry do |e| %>
              <%= e.hidden_field :user_id, value: user.id %>
            <% end %>
            <%= f.submit "チャットを始める", class:"btn btn-success user-show-chat my-2" %>
          <% end %>
        <% end %>
      <% end %>
    <% else %>
      <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
    <% end %>
  <% else %>
    <div class="row">
      <%= link_to edit_user_path(user), class: 'btn btn-outline-secondary btn-block' do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
    </div>
  <% end %>
  <h2 class="mt-3">New book</h2>

  <%= form_with model: book do |f| %>
    <div class="form-group">
      <label for="book_title">Title</label>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <label for="book_body">Opinion</label>
      <%= f.text_area :body, class: "form-control "%>
    </div>

    <div class="form-group">
      <label for="tag_name">Tag</label>
      <%= f.text_field :tag_name, class: "form-control" %>
    </div>

    <div class="form-group">
      <span><%= f.label :rate, 'Rate' %></span>
      <span id="evaluate-stars">
      <%= f.hidden_field :rate, id: :review_star%>
      </span>
    </div>


    <div class="form-group">
      <%= f.submit 'Create Book', class: "btn btn-success" %>
    </div>
  <% end %>

  <script>
  $(document).on('turbolinks:load', function() {
    $('#evaluate-stars').empty();
    $('#evaluate-stars').raty({
      size: 36,
      starHalf: "<%= asset_path('star-half.png') %>",
      starOn: "<%= asset_path('star-on.png') %>",
      starOff: "<%= asset_path('star-off.png') %>",
      scoreName: 'book[rate]',
      half: true,
    });
  });
  </script>

</div>

app/views/books/_rate.html.erb
<div id="star-rate<%= book.id %>"></div>
<script>
$(document).on('turbolinks:load', function() {
  $('#star-rate<%= book.id %>').empty();
  $('#star-rate<%= book.id %>').raty({
    starHalf: '<%= asset_path('star-half.png') %>',
    starOff : '<%= asset_path('star-off.png') %>',
    starOn  : '<%= asset_path('star-on.png') %>',
    half    : true,
    readOnly: true,
    score: <%= book.rate %>,
  });
});
</script>

app/views/books/edit.html.erb
<div class="container">

  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>

      <%= render 'error', model: @book %>

      <%= form_with model: @book do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <label for="book_body">Opinion</label>
          <%= f.text_area :body, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update Book', class: "btn btn-success" %>
        </div>
      <% end %>
      <%= link_to "Show", book_path(@book.id) %> |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <%= render 'error', model: @book %>
  <div class="row">

    <%= render 'left', user: current_user, book: @book %>

    <div class="col-md-8 offset-md-1">
      <h1>Books</h1>
      <%= link_to "新しい順", books_path(fast: "true") %> |
      <%= link_to "評価の高い順", books_path(rate_count: "true") %>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th>Tag</th>
            <th colspan="5"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= image_tag book.user.get_profile_image(50,50) %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>
              <td>
                <%= link_to search_path(range: "Tag", word: book.tags.map(&:tag_name).join(',')) do %>
                  <%= book.tags.map(&:tag_name).join(',') %>
                <% end %>
              </td>
              <td class="<%= book.id %>">
                <%= render 'favorites/favorite-btn', book: book  %>
              </td>
              <td>
                <p>コメント数：<%= book.book_comments.count %></p>
              </td>
              <td>
                <%= render 'rate', book: book %>
              </td>
              <td class="book-evaluation" date-score="<%= book.rate %>"></td>
              <td>
                <p>PV数：<%= book.views.count %></p>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">

    <%= render 'left', user: @book.user, book: @new_book, isRoom: @isRoom, room: @room, entry: @entry, roomId: @roomId %>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book.user.id) do %>
                <%= image_tag @book.user.get_profile_image(50,50) %><br>
                <%= @book.user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(@book.id) do %>
                <%= @book.title %>
              <% end %>
            </td>
            <td>
              <%= @book.body %>
            </td>
            <td class="<%= @book.id %>">
              <%= render 'favorites/favorite-btn', book: @book %>
            </td>
            <td>
              <p>コメント数：<%= @book.book_comments.count %></p>
            </td>
            <td>
              <%= render 'rate', book: @book %>
            </td>
            <td>
              <% if @book.user == current_user %>
                <%= link_to "Edit", edit_book_path, class: 'btn btn-sm btn-success' %>
              <% end %>
            </td>
            <td>
              <% if @book.user == current_user %>
                <%= link_to "Destroy", book_path(@book), class: 'btn btn-sm btn-danger',  method: :delete, "data-confirm" => "本当に削除しますか？"%>
              <% end %>
            </td>
            <td>
              <P>閲覧数：<%= @book.views.count %></P>
            </td>
          </tr>
        </tbody>
      </table>
      <table class="comment-view">
        <%= render 'book_comments/index', book: @book  %>
      </table>
      <div class="comment-box">
        <%= render 'book_comments/comment', book: @book, book_comment: @book_comment %>
      </div>
    </div>
  </div>
</div>